### ISSUE TITLE
Add example on integrate pubsub to service

### ISSUE THREAD

**Issue by vanhtuan0409** [NYTimes/gizmo#103]
Currently, I am implementing kind of message bus for each service.
I would like to see some example on how we should integrate pubsub into `Service` such as `JSONService`
If anyone can provide some sort of README or example. I would very much appreciate it :D

**Comment by jprobinson** [comment]
Hi there, @vanhtuan0409!

There actually are a couple examples in the `/examples` directory that combine gizmo/server with gizmo/pubsub:

https://github.com/NYTimes/gizmo/tree/master/examples/pubsub/api-sns-pub
https://github.com/NYTimes/gizmo/tree/master/examples/pubsub/api-kafka-websocket-pubsub

In both scenarios,  the pubsub.Publisher or pubsub.Subscriber are part of the gizmo/server.Service implementation so they can be easily injected into each request handler.

For example, here's a pubsub.Publisher that's an attribute of a JSONService: 
https://github.com/NYTimes/gizmo/blob/master/examples/pubsub/api-sns-pub/service/service.go#L17-L19

Within the handler, we get a hold of the injected publisher and publish with it: 
https://github.com/NYTimes/gizmo/blob/master/examples/pubsub/api-sns-pub/service/cats.go#L17

I hope this helps!

**Comment by vanhtuan0409** [comment]
@jprobinson Thank you very much for such a quick response
I can understand clearly how you inject pubsub.Publisher into Service
But I am not clear how a Service can subscribe to an event
In my imagination, it should be initialized together with the service in `NewStreamService` func
Should I create a special Subscribe function to initialize pubsub.Subscriber and dispatch the event to the corresponding Handler

**Comment by jprobinson** [comment]
Sorry, I'm not quite sure I follow your use case.

It sounds like you want to have a pubsub.Subscriber within a server.Service? Generally, I keep those as separate entities unless you want to do something similar to the websocket/Kafka example I shared.

If you're looking to do a _push_-style subscriber, you're likely fine just using the HTTP endpoints as a means for consuming messages POSTed by some publisher outside the service as gizmo/pubsub.Subscriber is generally for _pull_-style subscribers.

Here are some docs that cover the two styles of subscriptions for GCP's PubSub: https://cloud.google.com/pubsub/docs/subscriber#push_pull

**Comment by vanhtuan0409** [comment]
I mean do you consider this type of Subscribe normal?

```go
type MyService struct {
	pub pubsub.Publisher
	sub pubsub.Subscriber
}

func NewMyService(p pubsub.Publisher, s pubsub.Subscriber) *MyService {
	service := &MyService{p, s}
	go service.Subcribes()
	return service
}

func (s *MyService) Subcribes() {
	msgs := s.sub.Start()
	for {
		select {
			case msg := <- msgs:
				// doing something
				s.MessageHandleFunc(msg.Message())
		}
	}
}

func (s *MyService) JSONEndpoints() map[string]map[string]JSONEndpoint {
	
}
func (s *MyService) JSONMiddleware(JSONEndpoint) JSONEndpoint {

}
func (s *MyService) MessageHandleFunc(msg proto.Message) error {
	// doing something
}
```

**Comment by jprobinson** [comment]
That seems reasonable to me.

If the health of your API service is dependent upon the health of the subscriber, you may want to add a custom health check to your server that keeps an eye on things.
