### ISSUE TITLE
PubSub GCP MaxExtension not changeable

### ISSUE THREAD

**Issue by wezzle** [NYTimes/gizmo#111]
Hi,

I'm trying to use the GCP Pubsub throught `github.com/NYTimes/gizmo/pubsub/gcp` but my receiver is running an import with a long duration surpassing the `defaultMaxExtension = 60 * time.Second` as defined on [gcp.go:51](https://github.com/NYTimes/gizmo/blob/master/pubsub/gcp/gcp.go#L51). Causing the message to be resend because the receiver failed to `Ack()` the message.

Maybe i'm missing something but i don't see a way to change the MaxExtension on the underlying [subscription's ReceiveSettings](https://godoc.org/cloud.google.com/go/pubsub#ReceiveSettings)

I guess this requires a change in the code to make customisable? I'm happy to send in a pull request but would like to hear if it's needed an how you would like to see it implemented?

**Comment by jprobinson** [comment]
Congrats! 🎉 You're the first user to run into the 60s limit :grin:

I've been bothered by this myself. For now, I'm fine with adding a `pubsub.ReceiveSettings` parameter to the `NewSubscriber` func.

PRs are definitely appreciated! I'm sure I can find a volunteer for the work if you're busy.

**Comment by wezzle** [comment]
No it's ok, I'm working on it right now anyways.

Would you be in favour of adding a struct to gizmo's pubsub/gcp so including the google cloud pubsub package would not be a requirement? Or just directly use the gpubsub.ReceiveSettings?

**Comment by jprobinson** [comment]
I'm find with just using the gpubsub.ReceiveSettings, no need for us to make a config that mimics it.

Let's go with the using a setter func for now. This would be an annoying breaking change.

**Comment by wezzle** [comment]
I'll continue this tomorrow, i'm on European time. One thing I noticed is that with a setter it requires creating a func on both `subscriber` as `subscriptionImpl`. That seems a bit ugly too but i'll send in the pull request as soon as possible so you can review it.

**Comment by jprobinson** [comment]
Let's change the `NewSubscriber` to return a `*pubsub/gcp.Subscriber` (instead of the interface) so we wont need to alter the overall `pubsub.Subscriber` interface and folks can have access to the 
 new setter method.

**Comment by wezzle** [comment]
The pull request is here: #112 

Please let me know if this is how you pictured it.
