### ISSUE TITLE
PubSub GCP Attributes (keys)

### ISSUE THREAD

**Issue by wezzle** [NYTimes/gizmo#113]
Hi,

One more thing i came across: the [gcp.Publish](https://github.com/NYTimes/gizmo/blob/master/pubsub/gcp/gcp.go#L143) and [gcp.PublishRaw](https://github.com/NYTimes/gizmo/blob/master/pubsub/gcp/gcp.go#L152) have a param `key string`.

However this is converted to `Attributes: map[string]string{"key": key}` [here](https://github.com/NYTimes/gizmo/blob/master/pubsub/gcp/gcp.go#L155). Wouldn't it be better to allow a map in the params of those functions?

Would of course mean a breaking change, but the functionality is partially broken now anyways?

**Comment by jprobinson** [comment]
I guess I really only had the key in there for Kafka and haven't had a need for the Google PubSub attributes as I tend to put all my domain information into the message itself.

I'm interested...what's your use case for Attributes?

**Comment by wezzle** [comment]
It'a not blocking for me neither as I can always put everthing in the message as you did. The reason I wanted to use the attributes was to seperate job metadata like an ID from the actual message. In my case I'm using it to publish a message with import params to the topic and have multiple workers pull and run the imports. Sending the ID along with the message would mean I'd have to split it from the import params first before using them in the actual import.

With the current code I can send the ID as the only key's value but the name will always be "key".

So not blocking in any way but allowing the user to send multiple Attributes if needed would be nice I think.

PS. love how responsive you are!

**Comment by wezzle** [comment]
Just realised I wasn't able to use attributes at all because there was no way of accessing them. I've submitted another pull request allowing access to the attributes: #114 

I've not yet touched the publishing part of attributes, but I would prefer being able to use them, still unsure how to do that without breaking code though.
