### ISSUE TITLE
Clean up README.md

### ISSUE THREAD

**Issue by jprobinson** [NYTimes/gizmo#116]
We have far too much documentation in the README, which makes keeping things up to date rather difficult.

We should trim down the README to just cover the highlights and purpose of gizmo.

**Comment by jMuzsik** [comment]
Hi, I'd be willing to spend an indeterminate amount of time (like a day or two) researching/making the README much more concise and easy to understand

**Comment by jprobinson** [comment]
\o/ Thanks @jMuzsik!!!

I think it'd be best to just cut out most of the core documentation in there and leave that to the doc.go and code itself.

If we could cut it down to just a basic explanation and a table of contents for all the sub packages, I think it'd be a great start.

**Comment by jMuzsik** [comment]
Got it! Will begin asap, forking now

**Comment by jprobinson** [comment]
https://github.com/NYTimes/gizmo/pull/139
