### ISSUE TITLE
Unable to build minimal example

### ISSUE THREAD

**Issue by aackerman** [NYTimes/gizmo#128]
I don't write a lot of go. I feel like there's something critical I'm missing in being unable to run this program, it doesn't even include a service. Any help would be appreciated.

I installed go from brew

```
❯ go version
go version go1.9.1 darwin/amd64
```

I'm attempting to use `dep` to install dependencies. So I ran `dep init` and `dep ensure` with the example below.

```go
package main

import (
	"github.com/NYTimes/gizmo/server"
)

func main() {
	server.Init("test-server", nil)
	if err = server.Run(); err != nil {
		server.Log.Fatal("unable to run server: ", err)
	}
}
```

```
❯ go build main.go
# test/vendor/github.com/NYTimes/gizmo/server
vendor/github.com/NYTimes/gizmo/server/router.go:87:17: cannot use h (type http.Handler) as type http.HandlerFunc in assignment: need type assertion
```

Is there anything I can do on my end to fix this or is this really an issue in `gizmo`?

**Comment by jprobinson** [comment]
Howdy!

Unfortunately, the httprouter package used by gizmo last tagged a release in 2015 and they've made breaking changes since then.

Since dep uses the highest version by default, an override is required to point at master. Check out the bottom of this example should help: https://github.com/NYTimes/gizmo/blob/master/examples/servers/reading-list/Gopkg.toml

Hope this helps!

**Comment by aackerman** [comment]
@jprobinson it would have helped me immensely if this was part of the README. Would you accept a PR that adds the following to the README?

> The `httprouter` package used by gizmo last tagged a release in 2015 and they've made breaking changes since then.
> Since `dep` uses the highest version by default, an override is required to point at master. Check out the bottom of this example should help: https://github.com/NYTimes/gizmo/blob/master/examples/servers/reading-list/Gopkg.toml

Or maybe asking the maintainers of the `httprouter` project to tag a later version.

**Comment by jprobinson** [comment]
I'd vote for the latter. There might be an issue on httprouter already. If
you haven't already, a comment or a +1 on the issue would be appreciated.
