### ISSUE TITLE
Update tag

### ISSUE THREAD

**Issue by marwan-at-work** [NYTimes/gizmo#140]
Would it be possible to up the tag of Gizmo to `v0.0.2`? Would love to “properly” update our dependencies to fix the panic on 404s. Thanks

**Comment by jprobinson** [comment]
You got it, boss.

**Comment by jprobinson** [comment]
https://github.com/NYTimes/gizmo/releases/tag/v0.1.1

This work?

**Comment by marwan-at-work** [comment]
Yep, updated perfectly. Thank you!
