### ISSUE TITLE
Gizmo uses request path incl. GET parameters for Prometheus http metrics labels

### ISSUE THREAD

**Issue by oliver-nyt** [NYTimes/gizmo#144]
Somehow `TimedAndCounted` [here](https://github.com/NYTimes/gizmo/blob/bec4a802d517edc9ce935efbf4981b0e81db509d/server/metrics.go#L147) is passed the full request path INCLUDING the GET parameters which messes up the labels pretty good.

Not sure when that started or if that has always been the case but we should strip GET parameters from the string before using it as a label.

**Comment by oliver-nyt** [comment]
I dug around a little and it is recording the full path in the handler only for 404s which, unfortunately, makes sense.

The issue is here: https://github.com/NYTimes/gizmo/blob/master/server/simple_server.go#L107

We default to using the full request path when we can't resolve the request path to a handler.

One way o fix this would be to use a default of e.g. `__404` after line 108 (e.g. only when we use a GorillaRouter) and leave it at that when we can't find a matching handler.

Thoughts @jprobinson ?

**Comment by jprobinson** [comment]
Howdy @oliver-nyt! I think what you're proposing sounds reasonable. I imagine if we start seeing a large number of 404s, we can always fall back to logs to see _which_ URIs specifically are bad.

Go ahead and make a PR if you have the time.

**Comment by oliver-nyt** [comment]
👍
