### ISSUE TITLE
proposal: integrate Go CDK pubsub

### ISSUE THREAD

**Issue by jba** [NYTimes/gizmo#178]
The [Go Cloud Development Kit](https://gocloud.dev), an open-source product of Google's Go team, is a set of high-level APIs that are designed to work across multiple cloud and on-prem providers. For example, our [`blob`](https://godoc.org/gocloud.dev/blob) package lets the same code read and write data to Amazon S3, Google Cloud Storage, Azure Storage or a local filesystem.

We'd like to integrate our [Go CDK pubsub API](https://godoc.org/gocloud.dev/pubsub) with Gizmo.  We'd add a `pubsub/gocdk` directory with implementations of the four pubsub interfaces and config support. Gizmo would immediately gain two pubsub implementations—Azure and RabbitMQ—and would benefit from any future Go CDK integrations.

**Comment by jba** [comment]
@jprobinson Would you be open to a PR for this?

**Comment by jprobinson** [comment]
Howdy @jba,

I really appreciate you all considering Gizmo with the Go CDK, but we're actually at a point where we're attempting to consolidate Gizmo's dependencies to only the technology The New York Times is using internally. As an example, [we just removed most of our alternate monitoring providers from the SimpleServer](https://github.com/NYTimes/gizmo/pull/177).

With that in mind, we don't have any plans to move forward with Azure's cloud services and we prefer our developers to lean on managed queueing/event sourcing tools, so RabbitMQ is not in our current recommended tech stack. At this point, I think we'd prefer to keep the CDK separate from this project.
