### ISSUE TITLE
go.sum mismatch at head

### ISSUE THREAD

**Issue by jba** [NYTimes/gizmo#179]
I cloned this repo and ran `make build`. It failed with
```
verifying github.com/influxdata/platform@v0.0.0-20181127204756-e2959c61b782: checksum mismatch
        downloaded: h1:L2DsZmSjI2ySLb1AaYtUkBjMcgRZC1DsL9fcagszDv4=
        go.sum:     h1:ekuRYg65KyXed1eWHMYKBNfa8Zw57UbBef4RTKPxiLY=
```

**Comment by jprobinson** [comment]
You’ve run into the joys of https://github.com/golang/go/issues/29278

It works in Travis as Go modules has not been enabled there.

I’ll try and clean it up soon. For now, removing that checksum line allows the system to build.

**Comment by jba** [comment]
Yes it does, thanks.
