### ISSUE TITLE
Extract App Engine From server/kit

### ISSUE THREAD

**Issue by marwan-at-work** [NYTimes/gizmo#185]
The App Engine Set Up (such as tracing, metrics, and logging) does not have to be locked with server/kit, this way you can use it with the SimpleServer

**Comment by jprobinson** [comment]
If the abstraction fits well with both servers, I'm down for doing this. If it ends up being a square peg/circle hole problem, it may be fine to just put similar hooks into the SimpleServer.

As most users of the `SimpleServer` are using Prometheus, we'll likely need to do some tests to see if the OpenCensus Prom exporters give the same functionality as we have now. From there, we'll need to look to add some small config option in each server to select/register the appropriate OC exporters.
