### ISSUE TITLE
server.Register should error if it is called more than once

### ISSUE THREAD

**Issue by jprobinson** [NYTimes/gizmo#19]
https://github.com/NYTimes/gizmo/pull/18 brought up the issue that there is nothing to prevent users from registering multiple services on a single Gizmo server, which I think is against the microservice philosophy.

To force users to only have 1 Service per Server, we should change the 'Register' methods to error if a service has already been registered.

**Comment by stuartweir** [comment]
Hi @jprobinson, is this something a newer Go dev could handle? If so, I'd be down to try my hand at it if no else has

**Comment by jprobinson** [comment]
Howdy @stuartweir. 

This should be a pretty simple, straight forward change.

The simplest implementation I can think of would involve a bool flag indicating a service has been registered. If it's set, we should return some exported error type (maybe a `server.MultiRegisterErr`?) that all `Server` implementations can return in this scenario.

**Comment by gabelev** [comment]
Hey @stuartweir are you still taking this on? Was thinking about doing a PR for it.

**Comment by stuartweir** [comment]
Hey Gabriel, go for it! Yeah I've been sidetracked with a number of other things :/
