### ISSUE TITLE
Deprecated Types Should Have Been Removed Before 1.0

### ISSUE THREAD

**Issue by marwan-at-work** [NYTimes/gizmo#190]
Any reason not to have removed this router since it was deprecated a year ago before Gizmo became stable? https://github.com/NYTimes/gizmo/pull/133

Would we be comfortable removing those after 1.0? Or should we remove then put a 2.0 tag?

**Comment by jprobinson** [comment]
I forgot about that fella. Thought I had removed it already. Good catch.

I'm fine with keeping this within the 1.x universe.
