### ISSUE TITLE
server/kit does not flush its stack driver exporter 

### ISSUE THREAD

**Issue by marwan-at-work** [NYTimes/gizmo#193]
Servers should call https://godoc.org/contrib.go.opencensus.io/exporter/stackdriver#Exporter.Flush
before they terminate so that any metrics can be exported before termination. 

It makes the code a bit ugly because you have to propagate the exporter all the way back up to the `main` function so that you can `defer exporter.Flush()`  

However, it's probably required if users want accurate metrics. Otherwise, ignoring it is fine with me as well since it makes the code more readable but we might want to note that somewhere in the documentation.

**Comment by jprobinson** [comment]
For the logger, we hold onto the "Close()" method within the server so we can call it on shutdown: https://github.com/NYTimes/gizmo/blob/master/server/kit/kitserver.go#L29-L30

We can probably add another "flushFunc" field for each exporter, can call them within our shutdown hook: https://github.com/NYTimes/gizmo/blob/master/server/kit/kitserver.go#L335-L338

What do you think?

**Comment by jprobinson** [comment]
Closed in #192
