### ISSUE TITLE
Potential TimeSeries Race/Error With StackDriver

### ISSUE THREAD

**Issue by marwan-at-work** [NYTimes/gizmo#196]
The docs below mention that every TimeSeries written must be fully unique which is why it adds a "go-process" label, however, we seem to explicitly remove the "go-process" labels but only add a "projectID" and "deploymentID"...However, once we have multiple instances of the same application, wouldn't that mean we are violating the StackDriver rules? 

See this document for the rules:
 https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/master/stackdriver.go#L179:L194

See here for the override: 
https://github.com/NYTimes/gizmo/blob/master/server/kit/stackdriver.go#L36

**Comment by jprobinson** [comment]
This makes sense. I hadn't tried to export views yet (GAE gives us what I need, generally) so is very possible nothing has been going through.  I remember now I had asked about this in the GAE forums and got crickets so just moved forward with our tracing working as it was.

Perhaps we can just provide `nil` here and resolve the issue? I'm just unsure how it will behave in the GAE std environment without further testing. 🤞 os.Hostname() and os.Pid() return something useful.

**Comment by marwan-at-work** [comment]
@jprobinson Yes, I'll remove it from this PR https://github.com/NYTimes/gizmo/pull/192 to be compliant with their docs and we can test onwards. Thanks!

**Comment by jprobinson** [comment]
Resolved in #192
