### ISSUE TITLE
aws.subscriber not thread safe

### ISSUE THREAD

**Issue by alessandrozucca** [nytimes/gizmo#211]
In our company we made the wrong assumption that the [aws.subscriber](https://github.com/nytimes/gizmo/blob/master/pubsub/aws/aws.go#L297) was thread safe so we were spinning up multiple workers (in different go routines) that were sharing the same subscriber.

As soon as one was stopped, [all others were too](https://github.com/nytimes/gizmo/blob/master/pubsub/aws/aws.go#L381)

would be possible to add a warning in the README.md saying that it isn't thread safe?

**Comment by alessandrozucca** [comment]
One solution what we are thinking about is to create a pool of subscribers for a given queue, and each worker takes them from this pool

**Comment by jprobinson** [comment]
Howdy @alessandrozucca, when I'm fanning out messages to multiple workers from a single subscriber, I hand each goroutine a reference to the channel returned by `Start()`. That allows the subscriber to rely on the Go channel primitives to fan work out.

Is your problem that your bottleneck is consuming messages off of SNS? If that's the case, I'd suggest creating multiple subscriber instances and consuming them in separate goroutines/processes.

**Comment by jprobinson** [comment]
A _very_ rough example of what I mentioned in my first block looks something like this:

```go

func run(sub pubsub.Subscriber) {
	stream := sub.Start()

	for i := 0; i < maxWorkers; i++ {
		go consumeStream(stream)
	}

}

func consumeStream(stream <-chan pubsub.SubscriberMessage) {
	for item := range stream {
		fmt.Println(item)
	}
}
```

**Comment by alessandrozucca** [comment]
Thanks for your quick reply @jprobinson 

Yes ideally we wanted to consume messages as fast as possible in parallel, but for now we will just pass in the channel to the workers.
