### ISSUE TITLE
Remove Prefix() from `server.Service`, add it to `config.Server`

### ISSUE THREAD

**Issue by jprobinson** [NYTimes/gizmo#25]
Since a prefix can an optional value for services, we should not force everyone to implement it, especially since the value is likely to be immutable.

We should remove the method from the `server.Service` interface, include it's value as an attribute in `config.Server` and then change the `server.Register` implementations to utilize it.

**THIS WILL BE A BREAKING CHANGE!**
If possible, it'd be nice if we could provide a small utility that would see a `Prefix()` implementation, remove it and then add a line about `server.Init(...)` in main.go to do a `config.Server.Prefix = "xyz"` on the line above.

**Comment by marzagao** [comment]
@jprobinson Can we close this based on the work you did for NYTimes/gizmo#44 ?

**Comment by jprobinson** [comment]
Sounds good to me, boss. 👍
