### ISSUE TITLE
Empty prefix cause an errors

### ISSUE THREAD

**Issue by gaplyk** [NYTimes/gizmo#26]
When prefix is empty mux failed to add subroutes. It does not return any kind of errors, just silently fail.

I already made a fix:
https://github.com/gaplyk/gizmo/blob/master/server/simple_server.go#L180
Can create pull request if this is will be considered as an issue.

**Comment by jprobinson** [comment]
This will get taken care of when https://github.com/NYTimes/gizmo/issues/25 is completed.

**Comment by jprobinson** [comment]
This was fixed as a part of the changes in PR #44.
