### ISSUE TITLE
RPC service does not expose HTTP endpoints

### ISSUE THREAD

**Issue by labkode** [NYTimes/gizmo#35]
I just cloned the  [RPC example](https://github.com/NYTimes/gizmo/blob/master/examples/servers/rpc/) but the HTTP endpoints are not exposed.

I also had to modify the code because in newer versions of gRPC you have to add grpc.WithInsecure() when calling grpc.Dial(...)

Any clue why the http endpoints are not being exposed ?

**Comment by jprobinson** [comment]
Hi @labkode, thanks for catching this!

You're right, the RPC server was busted. We somehow removed a couple essential goroutines and go the tcp listeners got swapped in the server. 

I've patched everything up in a commit I just pushed to master: https://github.com/NYTimes/gizmo/commit/f5b781af819fd4ff6a015260663845976d02be5c

Thanks for trying out Gizmo!

**Comment by labkode** [comment]
Hi @jprobinson,

I think Gizmo is a really great project with lower learning curve than go-kit and much simpler.
If I may add a suggestion, it would be great to version the dependencies of Gizmo ...
A `godep save` using `go1.6` should do the job.

Thanks for this great framework

**Comment by jprobinson** [comment]
Thanks for the feedback. I've been thinking about adding a `/vendor` directory to the project, but have been leaning towards the philosophy that only _end user_ projects should do the vendoring. After seeing how often gRPC changes, though, I may change my mind. Feel free to make an issue to add vendoring to the project.
