### ISSUE TITLE
server.MonitorRPCRequest() does not write to the RPCAccessLog

### ISSUE THREAD

**Issue by labkode** [NYTimes/gizmo#36]
Still playing with the RPC example I have discovered that the [server.MonitorRPCRequest()](https://github.com/NYTimes/gizmo/blob/master/examples/servers/rpc/service/mostpopular.go#L18) does not write to the RPC log file. 

Any hint about a possible solution ? Thx

**Comment by jprobinson** [comment]
`MonitorRPCRequest` was creating a `logrus.Entry`, but it wasn't actually _logging_ it. I've added a simple INFO level "access" message to make the library emit something: https://github.com/NYTimes/gizmo/commit/970f99b8183602df8fde8ada021400f0be93681f

Another nice catch! RPCServer has needed some love.
