### ISSUE TITLE
Add Read Preference and Tags to Mongo config

### ISSUE THREAD

**Issue by danny-cassidy** [NYTimes/gizmo#53]
Rather than rely on a MasterHost config value, which can change during elections, it would be more flexible to use Mongo's built in support for read preference and tags to constrain which nodes in the Hosts field can be used. 

If these configurations are set, the MongoDB object can supply these to the mgo Session object before returning it to the client via:

https://godoc.org/gopkg.in/mgo.v2#Session.SetMode (Read Preference)
https://godoc.org/gopkg.in/mgo.v2#Session.SelectServers (Tags)

**Comment by jprobinson** [comment]
Sounds like a good idea. I usually end up calling `SetMode` right after calling Gizmo's `config.MongoDB.Must()` anyways.

@danny-cassidy do you want to take a whack at adding these for your first Gizmo PR? If not, I can find some time to do this in the next day or two.

**Comment by danny-cassidy** [comment]
Yeah, I'd love to submit a PR for this. 👍

**Comment by jprobinson** [comment]
:+1: Looking forward to it!

**Comment by jprobinson** [comment]
This was resolved in PR #54
