### ISSUE TITLE
Allow ServerOption(s) to be passed into grpc Server

### ISSUE THREAD

**Issue by danny-cassidy** [nytimes/gizmo#64]
grpc supports various configurable options when creating a new rpc server. 

`func NewServer(opt ...ServerOption) *Server`

It would be nice if these options can be managed via a new Config type or some other solution. 

I can work on this if it sounds reasonable.

**Comment by jprobinson** [comment]
I like the idea of turning `server.Config` into a set of `server.ServerOptions`.

Go ahead and put together an initial implementation and we can work through the details.

Thanks for initiating this!

**Comment by jprobinson** [comment]
This RPC server no longer exists.
