### ISSUE TITLE
Error When i use MYSQL config out of appengine sdk

### ISSUE THREAD

**Issue by felipeweb** [NYTimes/gizmo#73]
```
GOROOT=/usr/local/Cellar/go/1.7/libexec
GOPATH=/Users/felipeweb/Code/go
/usr/local/Cellar/go/1.7/libexec/bin/go build -o "/private/var/folders/3x/ydvg5kjn6pvgwmp21lhytpcw0000gn/T/Build main.go and rungo" /Users/felipeweb/Code/go/src/bitbucket.org/lebre/lebre/main.go
package main
	imports bitbucket.org/lebre/lebre/service
	imports github.com/NYTimes/gizmo/server
	imports google.golang.org/appengine
	imports google.golang.org/appengine/internal
	imports google.golang.org/appengine/internal/log: use of internal package not allowed
```

**Comment by jprobinson** [comment]
Hi @felipeweb, could you please provide a some more info on your issue? 

Are you using the latest versions of all your dependencies? Is this an Flexible VM? Standard App Engine VMs will not work with Gizmo.

**Comment by felipeweb** [comment]
I don't use app engine, but here is the Go code that cause the error https://gist.github.com/felipeweb/bea7ce6654e04fcf3f9dfdab604e47f2 and https://gist.github.com/felipeweb/70f8698455ac205e81fd027568ce3607.

when i remove the https://gist.github.com/felipeweb/70f8698455ac205e81fd027568ce3607#file-user-go-L13 and get db using sql package the app ok.
 here is my cfg https://gist.github.com/felipeweb/93acd8df156b48bbddf34ecbf8784a4b

**Comment by felipeweb** [comment]
@jprobinson i'm sorry about that one of my dependencies wasn't in the last version when i update fix that. thank you for your attention
