### ISSUE TITLE
Question: how can I organize folders for multiple services?

### ISSUE THREAD

**Issue by alioygur** [NYTimes/gizmo#80]
Hello,

I have looked examples folder but all examples has single service. So how can I organize folder multiple services.

Can I define multiple services in main.go file? if I can, what about service's config.json file ?

Sorry my bad english.

**Comment by jprobinson** [comment]
Hi there!

Great question! We've been working on standardizing repo structure at NYT and have been using a structure somewhat based on the approaches described by Ben Johnson and Peter Bourgon:

https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1
https://peter.bourgon.org/go-best-practices-2016/#repository-structure

In most of my recent projects I've had the need for a reusable set of domain models and interfaces across an API, a 'publisher' CLI tool and sometimes even a  'subscriber' daemon. Given the approaches listed above, I've been gravitating to something that looks like this:
```
example-project
├── db.go
├── db_test.go
├── example.go
├── example_test.go
├── exampletest
│   └── example.go
├── api
│   ├── main.go
│   └── service
│       ├── endpoint.go
│       ├── endpoint_test.go
│       └── service.go
├── publisher
│   ├── main.go
│   └── service
│       ├── publish.go
│       └── publish_test.go
└── subscriber
    ├── main.go
    └── service
        ├── sub.go
        └── sub_test.go
```
The domain models, interfaces and main implementations are in the base of the repo. 'Test/Mock' implementations of domain interfaces exist in a `__test` subpackage for the api, pub and sub to all use in their testing.

As for the configuration files, I tend to have those in some kind of configuration management tool like Puppet or consul-template where they get injected at build/deploy time.

I hope this helps!

**Comment by alioygur** [comment]
@jprobinson thank you!
