### ISSUE TITLE
Add an HTTP request tracing header

### ISSUE THREAD

**Issue by akhileshnayak** [NYTimes/gizmo#91]
I'm not sure how many folks at the Times are using gizmo but if you think it would be useful maybe we could add a request id header (X-NYT-Request-Id) to gizmo? If that's too Times specific maybe we could use X-Request-ID like Heroku does (https://devcenter.heroku.com/articles/http-request-id)? This header would be parsed from requests coming into a service and passed by the service to other services in HTTP requests that it makes. It would also be logged with all log statements related to a particular web transaction.

**Comment by jprobinson** [comment]
I'm not sure we'd want to add this kind of stuff on by default, but Gizmo does have hooks for HTTP and JSON middlewares, which would be an excellent place to put such a tracing tool.

In the future (hopefully near), we should also have a `KitServer` which exposes hooks for go-kit middleware, which includes support for open tracing: https://godoc.org/github.com/go-kit/kit/tracing/opentracing

**Comment by akhileshnayak** [comment]
Ah ok cool, makes sense.
