### ISSUE TITLE
Update the SNS publisher to handle AWS interface changes

### ISSUE THREAD

**Issue by jprobinson** [NYTimes/gizmo#93]
We need to add `AddPermissionWithContext`: https://travis-ci.org/NYTimes/gizmo/jobs/217293105

**Comment by scotts-nyt** [comment]
Fixed by PR https://github.com/NYTimes/gizmo/pull/94. Checks fail due to updates to gpubsub lib. Can fix by updating code to reflect changes or vendoring that dep to hash 2e6a95edb1071d750f6d7db777bf66cd2997af6c or tag v0.7.0.
